# Generated by Django 2.0.3 on 2018-03-29 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_starff',
            new_name='is_staff',
        ),
    ]
